from __future__ import annotations

# ----------------------------
# Concept -> layer field mapping (defaults)
# ----------------------------
DEFAULT_FIELD_MAP = {
    "date": "report_date",
    "municipality": "municipality",
    "accident_class": "accident_class",
    "accident_location": "accident_location",
    "impact_location": "impact_location",
    "impact_type": "impact_type",
    "light": "light",
    "traffic_control": "traffic_control",
    "traffic_control_condition": "traffic_control_condition",
    "road_jurisdiction": "road_jurisdiction",
    "env1": "environment_condition_1",
    "env2": "environment_condition_2",
    "location_id": "location_id",
    "location_type": "location_type",
    "map_x": "map_x",
    "map_y": "map_y",
    "veh_cnt": "involved_vehicles_cnt",
    "ped_cnt": "involved_pedestrians_cnt",
    "occ_cnt": "involved_occupants_cnt",
    "drv_cnt": "involved_drivers_cnt",
    "per_cnt": "involved_persons_cnt",
}

# ----------------------------
# Default decode tables (concept -> {raw_code -> label})
# ----------------------------
DEFAULT_DECODES = {
    "location_type": {"mri": "Intersection", "mrs": "Road segment"},
    "municipality": {
        "CL": "Clarington", "WH": "Whitby", "OA": "Oshawa", "UX": "Uxbridge",
        "SC": "Scugog", "AJ": "Ajax", "PI": "Pickering", "BR": "Brock",
    },
    "env1": {
        "1": "Clear", "2": "Rain", "3": "Snow", "4": "Freezing rain / hail",
        "5": "Drifting snow", "6": "Strong wind", "7": "Fog / mist / smoke / dust",
        "8": "Glare", "99": "Other",
    },
    "env2": {
        "1": "Clear", "2": "Rain", "3": "Snow", "4": "Freezing rain / hail",
        "5": "Drifting snow", "6": "Strong wind", "7": "Fog / mist / smoke / dust",
        "8": "Glare", "99": "Other",
    },
    "accident_location": {
        "1": "Non Intersection",
        "2": "Intersection related",
        "30": "Four-way",
        "31": "Offset",
        "32": "L intersection",
        "33": "Y intersection",
        "34": "T intersection",
        "35": "Roundabout",
        "97": "Other intersection",
        "4": "At/near private drive",
        "5": "At railway crossing",
        "6": "Underpass or tunnel",
        "7": "Overpass or bridge",
        "8": "Trail",
        "9": "Frozen lake or river",
        "10": "Parking lot",
        "11": "Turnaround",
        "12": "Service centre",
        "13": "Truck inspection station",
        "14": "Rest area",
        "98": "Other on highway",
        "99": "Other off highway"
        },
    "impact_location": {
        "1": "Within intersection",
        "2": "Through",
        "3": "Left turn",
        "4": "Right turn",
        "5": "Right turn channel",
        "6": "Two-way left turn",
        "7": "Passing",
        "8": "Shoulder-Left",
        "9": "Shoulder-Right",
        "10": "Not on roadway left side",
        "11": "Not on roadway right side",
        "12": "Off highway",
        "13": "Gore/bullnose",
        "14": "Crossover",
        "15": "Crosswalk",
        "16": "School crossing",
        "17": "Sidewalk",
        "18": "High occupancy toll (HOT)",
        "19": "High occupancy vehicle (HOV)",
        "20": "Bicycle (unprotected)",
        "21": "Bicycle (protected)",
        "22": "Transit",
        "23": "Parking",
        "24": "Speed change",
        "25": "Bus bypass",
        "99": "Other"
        },
    "impact_type": {
        "1": "Approaching head-on",
        "2": "Angle",
        "3": "Rear end",
        "4": "Sideswipe",
        "5": "Turning movement",
        "6": "Single motor vehicle unattended",
        "7": "Single motor vehicle other",
        "8": "Reversing",
        "40": "Sideswipe - Same direction",
        "41": "Sideswipe - Opposite direction",
        "99": "Other"
        },
    "light": {
        "1": "Daylight",
        "2": "Daylight-artificial",
        "3": "Dawn",
        "4": "Dawn-artificial",
        "5": "Dusk",
        "6": "Dusk-artificial",
        "7": "Dark",
        "8": "Dark-artificial",
        "99": "Other",
    },
    "traffic_control": {
        "1": "Traffic signal",
        "2": "Stop sign",
        "3": "Yield sign",
        "4": "Pedestrian crossover",
        "5": "Police control",
        "6": "School guard",
        "7": "School bus flashing light and stop arm",
        "8": "Traffic gate",
        "9": "Traffic control person",
        "10": "No control",
        "11": "Flashing beacon",
        "12": "Railway crossing",
        "13": "Pedestrian signal",
        "14": "Half signal",
        "99": "Other",
    },
    "traffic_control_condition": {
        "1": "Functioning",
        "2": "Non-functioning",
        "3": "Obscured",
        "4": "Missing/Damaged",
    },
    "road_jurisdiction": {
        "1": "Municipal (excl. Twp. Rd.)",
        "2": "Provincial highway",
        "3": "Township",
        "4": "County or district",
        "5": "Regional municipality",
        "6": "Private property",
        "7": "Federal",
        "99": "Other",
    },
    "accident_class": {
        "1": "Fatal",
        "2": "Injury",
        "3": "PDO",
        "4": "Unknown",
    },
}

FILTER_CONCEPTS = [
    ("municipality", "Municipality"),
    ("road_jurisdiction", "Road jurisdiction"),
    ("accident_class", "Accident class"),
    ("accident_location", "Accident location"),
    ("location_type", "Location type"),
    ("impact_type", "Impact type"),
    ("impact_location", "Impact location"),
    ("light", "Lighting"),
    ("traffic_control", "Traffic control"),
    ("traffic_control_condition", "Traffic control condition"),
    ("env1", "Environment condition 1"),
    ("env2", "Environment condition 2"),
]

SETTINGS_FIELD_MAP_KEY = "collision_analytics/field_map_json"
SETTINGS_DECODES_KEY = "collision_analytics/decodes_json"
